[workspace]
name = "aiida-nn-xtb"
version = "0.2.0"
description = "AiiDA Plugin for easier use of NN-xTB energy calculations"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
# Core Language
python = ">=3.11,<3.13"

# Chemistry
rdkit = ">=2024"

# Testing Framework
pytest = ">=8"

# Build and package Utilities
pip = "*"
setuptools = "<80"

# Data Processing & Export
zarr = ">=3.2.1,<4"
numpy = ">=2.4.6,<3"
rabbitmq-server = "3.12.*"
postgresql = "15.*"
xtb = ">=6.7.1,<7"

[pypi-dependencies]
aiida-nn-xtb = { path = ".", editable = true }
aiida-core = { version = ">=2.8.0,<3", extras = ["atomic_tools", "tui"] }

[tasks]
test = "pytest tests/ -v"
